### ISSUE TITLE
Code review of Members module

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#19]
Review the existing code and make comments on working and non-working parts.

**Comment by oj-lappi** [comment]
## Implementation
- [ ] The code works  
- [ ] The code is easy to understand  
- [ ] Follows coding conventions  
- [ ] Names are simple and if possible short  
- [ ] Names are spelled correctly  
- [ ] Names contain units where applicable  
- [ ] There are no usages of 'magic numbers'  
- [ ] All variables are in the smallest scope possible  
- [ ] All class, variable, and method modifiers are correct  
- [ ] There is no commented out code  
- [ ] There is no dead code (inaccessible at Runtime)  
- [ ] No code can be replaced with library functions  
- [ ] Required logs are present  
- [ ] Frivolous logs are absent  
- [ ] Debugging code is absent  
- [ ] No print() or similar calls exist  
  - Use logger if needed  
- [ ] No stack traces are printed  
- [ ] Catch clauses are fine grained and catch specific exceptions  
- [ ] Understandable exception messages  
- [ ] Exceptions are not eaten if caught, unless explicitly documented otherwise  
- [ ] Variables are not accidentally used with null values  
- [ ] Code is not repeated or duplicated  
- [ ] No complex/long boolean expressions  
- [ ] Ideal data structures are used  
- [ ] APIs and other public contracts check input values and fail fast  
- [ ] Files/Sockets/Cursors and other resources are properly closed even when an exception occurs in using them  
- [ ] using `with open(...)`  
- [ ] Null/None are not returned from any method  
- [ ] No object exists longer than necessary  
- [ ] Design patterns if used are correctly applied
- [ ] The [Law of Demeter](https://stackoverflow.com/questions/14718998/law-of-demeter-the-pragmatic-programmer) is not violated (optional)
- [ ] Methods return early without compromising code readability  

## Documentation
- [ ] Public methods are commented in clear language (if seen necessary) 
  - e.g
    ```
    def method(param1, param2=None):
    """ 
    Method description if not self explainatory

    param1 (int): the first parameter
    param2 (:obj: 'str', optional): The second parameter
    Returns bool: True if successful, False otherwise. 
    """
    ```
- [ ] Comments exist and describe rationale or reasons for decisions in code  
- [ ] All public methods/interfaces/contracts are commented describing usage  
- [ ] All edge cases are described in comments  
- [ ] All unusual behavior or edge case handling is commented  
- [ ] Data structures and units of measurement are explained  

## Security
- [ ] All data inputs are checked (for the correct type, length/size, format, and range)  
- [ ] Invalid parameter values handled such that exceptions are not thrown  
- [ ] No sensitive information is logged or visible in a stacktrace  

## Further implementations
- Freeform text, what is missing, what could be added, what is unnecessary?
