### ISSUE TITLE
Get development environment up and running

### ISSUE THREAD

**Issue by JaNord** [Datateknologerna-vid-Abo-Akademi/date-website#21]
- [x] Oskar Lappi
 - [x] Jimmy Fagerholm
 - [x] Wiljam Tschernij
 - [x] Max Lundström 
 - [x] Andre Nordström
 - [x] Jakob Nordman
 - [x] Daniel Nordström
 - [x] Kevin Karlsson

**Comment by JaNord** [comment]
Converted this to an issue since it seems that running the project for the first time isn't as straight-forward as it could be? Perhaps the readme should be updated at this point?

**Comment by nDny** [comment]
I ported the env file to also work on windows, have it locally somewhere. Should help those working in a suboptimal os.

Edit: They are in the develop-beta branch

**Comment by oj-lappi** [comment]
what is the point of copying example.env to $USER.env?

Is there some deeper meaning to it? Or is it just so that I don't accidentally push a new version of example.env to upstream?

**Comment by oj-lappi** [comment]
The events_event table does not exist when first cloning the repo:

![2019-12-06-011540_4480x1440_scrot](https://user-images.githubusercontent.com/8479687/70282351-2fbb7800-17c6-11ea-9470-dd50a2948273.png)

If you only do what the README tells you, this leads to an error when attempting to open the webpage

> web_1  | django.db.utils.ProgrammingError: relation "events_event" does not exist

run ```date-makemigrations``` before running ```date-migrate``` to solve this issue.

**Comment by JaNord** [comment]
Right now my .env variables aren't read properly (at all) when running date-start, apparently Danne had the same issue. Is there a fix for this other than inserting the variables into the docker yaml ?

**Comment by oj-lappi** [comment]
What system are you running? And what shell?

If the variables are in the shell, check with e.g. 

>echo $DATE_DB_PORT

then according to [this document](https://docs.docker.com/compose/compose-file/#variable-substitution) the environment variables should be substituted in.

I can think of two things:

 - your shell doesn't support "export" (maybe it's a csh?)
 - you're running from a different directory, and therefore reading the wrong docker-compose.yml file

These seem unlikely though.

## This should work anyway

You can copy **example.env** to **.env** and remove all the alias and export commands

That's a file called _.env_

[An .env file](https://docs.docker.com/compose/env-file/) should provide defaults for docker-compose

>_.env_ =

```
# DB port (disable in production)
DATE_DB_PORT=5432

# DB password
DATE_DB_PASSWORD=-
DB_PASSWORD=-

# DB-files path
DATE_DB_PATH="/local/path/for/db/files"

# Django port
DATE_DJANGO_PORT=8000

# Django secret key (keep production secret)
DATE_SECRET_KEY=-
SECRET_KEY=-

# Debug django (set to False in prod)
DATE_DEBUG=True

# Set django DEVELOP setting (set to False in prod)
DATE_DEVELOP=True
```

Since environment vars override defaults in .env, I would recommend not to source example.env if you want to use .env, to avoid confusion about where the values are coming from.

**Comment by JaNord** [comment]
I'm running Ubuntu and using the standard terminal. The funny thing is that e.g. `echo $DATE_DB_PORT` does print the value of the variable. Thought I'd share this as Danne also had the same issue, so it might come up for someone else in the future aswell.

Thanks for the suggestion, I'll give it a try!

**Comment by oj-lappi** [comment]
Ok, yeah, that's super weird. Let us know if you find out what the issue was!
